FROM ermiry/mongoc:buildev as builder

# cmongo
WORKDIR /opt/cmongo
COPY . .
RUN make -j4

############
FROM ubuntu:bionic

ARG BUILD_DEPS='wget unzip build-essential pkg-config gdb'
ARG RUNTIME_DEPS='ca-certificates libssl-dev'

RUN apt-get update && apt-get install -y ${BUILD_DEPS} ${RUNTIME_DEPS} && apt-get clean

# mongoc files
COPY --from=builder /usr/lib/x86_64-linux-gnu/libicudata.so.63 /usr/lib/x86_64-linux-gnu/libicudata.so.63
COPY --from=builder /usr/lib/x86_64-linux-gnu/libicuuc.so.63 /usr/lib/x86_64-linux-gnu/libicuuc.so.63
COPY --from=builder /usr/local/include/ /usr/local/include/
COPY --from=builder /usr/local/lib/libmongoc-1.0.so /usr/local/lib/libmongoc-1.0.so
COPY --from=builder /usr/local/lib/libbson-1.0.so /usr/local/lib/libbson-1.0.so

# cmongo
COPY --from=builder /opt/cmongo/bin/libcmongo.so /usr/local/lib/
COPY --from=builder /opt/cmongo/include/cmongo /usr/local/include/cmongo

RUN ldconfig

CMD ["/bin/bash"]
