name: CMongo Production Integration

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: CMongo production build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gcc make
        run: make TYPE=production

      - name: clean
        run: make clean

      - name: g++ make
        run: make TYPE=production CC=g++

  docker:
    name: Docker build test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ermiry/cmongo:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
