name: CMongo Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    name: CMongo tests
    runs-on: ubuntu-latest
    container:
      image: ermiry/mongoc:buildev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # compile
      - name: Compile Sources
        run: make TYPE=test COVERAGE=1
      - name: Compile Tests
        run: make TYPE=test COVERAGE=1 test

      # run
      - name: Unit Tests
        run: bash test/run.sh

      - name: Coverage
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: build
          fail_ci_if_error: true
          # verbose: true
