name: CMongo Version Check

on:
  push:
    branches:
      - '*beta'
      - 'main'
  pull_request:
    branches:
      - '*beta'
      - 'main'

jobs:
  build:
    name: CMongo build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: gcc make
        run: make
      - name: gcc tests
        run: make test

      - name: Check version
        run: LD_LIBRARY_PATH=bin ./test/bin/version